/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package baitapquanlysv;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Admin
 */
public class HSSV extends javax.swing.JFrame {

    /**
     * Creates new form HSSV
     */
    public HSSV() {
        initComponents();
        SelectHSSV();
    }
  Connection Con= null;
  Statement St = null;
  ResultSet Rs = null;
  
  public void SelectHSSV(){
       try {
        Con= DriverManager .getConnection("jdbc:sqlserver://localhost;encrypt=false;user=sa;password=123456;applicationName=LAPTOP-Q9EDFG23\\SQLEXPRESS;databaseName=DBBaiTapLon");
        St= Con.createStatement();
        Rs =St.executeQuery("Select* from SinhVien");
        tableBang.setModel(DbUtils.resultSetToTableModel(Rs));
       } catch (Exception e) {
           e.printStackTrace();
       }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textMASV = new javax.swing.JTextField();
        txtHOVATen = new javax.swing.JTextField();
        txtDiem = new javax.swing.JTextField();
        txtLop = new javax.swing.JTextField();
        jcbChuyenNganh = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBang = new javax.swing.JTable();
        bntTHem = new javax.swing.JButton();
        bntSua = new javax.swing.JButton();
        bntXoa = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        bntTimkiem = new javax.swing.JButton();
        bntdelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("QUẢN LÝ SINH VIÊN ");

        jLabel2.setText("Mã Sinh Viên");

        jLabel3.setText("Họ và Tên ");

        jLabel4.setText("Chuyên Nghành");

        jLabel5.setText("Điểm ");

        jLabel6.setText("Lớp");

        textMASV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textMASVActionPerformed(evt);
            }
        });

        txtHOVATen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHOVATenActionPerformed(evt);
            }
        });

        txtDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiemActionPerformed(evt);
            }
        });

        txtLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLopActionPerformed(evt);
            }
        });

        jcbChuyenNganh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Công nghệ thông tin", "Luật", "Kế toán", "QTKD" }));

        tableBang.setBackground(new java.awt.Color(153, 204, 255));
        tableBang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "MaSV", "Ho Va Ten", "Chuyen Nganh", "Lớp", "Điểm"
            }
        ));
        tableBang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBang);

        bntTHem.setText("Thêm");
        bntTHem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntTHemMouseClicked(evt);
            }
        });
        bntTHem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTHemActionPerformed(evt);
            }
        });

        bntSua.setText("Sửa");
        bntSua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntSuaMouseClicked(evt);
            }
        });
        bntSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntSuaActionPerformed(evt);
            }
        });

        bntXoa.setText("Xóa");
        bntXoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntXoaMouseClicked(evt);
            }
        });
        bntXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntXoaActionPerformed(evt);
            }
        });

        jLabel7.setText("Mã sinh viên");

        bntTimkiem.setText("tìm kiếm ");
        bntTimkiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntTimkiemMouseClicked(evt);
            }
        });
        bntTimkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntTimkiemActionPerformed(evt);
            }
        });

        bntdelete.setText("Delete");
        bntdelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bntdeleteMouseClicked(evt);
            }
        });
        bntdelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntdeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(387, 387, 387)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbChuyenNganh, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtHOVATen, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(textMASV, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtLop, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(171, 171, 171)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bntTimkiem))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(bntTHem)
                        .addGap(82, 82, 82)
                        .addComponent(bntSua)
                        .addGap(90, 90, 90)
                        .addComponent(bntXoa)
                        .addGap(90, 90, 90)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bntdelete)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 950, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(textMASV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtHOVATen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(txtDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bntTimkiem)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jcbChuyenNganh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bntTHem)
                            .addComponent(bntSua)
                            .addComponent(bntXoa)
                            .addComponent(bntdelete))
                        .addGap(37, 37, 37)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textMASVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textMASVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textMASVActionPerformed

    private void txtHOVATenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHOVATenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHOVATenActionPerformed

    private void txtDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiemActionPerformed

    private void txtLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLopActionPerformed

    private void bntTHemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTHemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntTHemActionPerformed

    private void bntSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntSuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntSuaActionPerformed

    private void bntTimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntTimkiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntTimkiemActionPerformed

    private void bntTHemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntTHemMouseClicked
         if(textMASV.getText().isEmpty()||txtHOVATen.getText().isEmpty()|| txtDiem.getText().isEmpty()||txtLop.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "không được để rỗng");
        }else{
        try {
            Con= DriverManager .getConnection("jdbc:sqlserver://localhost;encrypt=false;user=sa;password=123456;applicationName=LAPTOP-Q9EDFG23\\SQLEXPRESS;databaseName=DBBaiTapLon");
             PreparedStatement add = Con.prepareStatement("insert into SinhVien Values(?,?,?,?,?)");
             add.setString(1, textMASV.getText());
             add.setString(2, txtHOVATen.getText());
             add.setString(4, txtLop.getText());
             add.setInt(5, Integer.valueOf(txtDiem.getText()));
             add.setString(3, jcbChuyenNganh.getSelectedItem().toString());
             int row = add.executeUpdate();
             JOptionPane.showMessageDialog(this, "Thêm Thành công ");
             Con.close();
             SelectHSSV();
        } catch (Exception e) {
            e.printStackTrace();
         } 
        }
    }//GEN-LAST:event_bntTHemMouseClicked

    private void tableBangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBangMouseClicked
            DefaultTableModel model = (DefaultTableModel) tableBang.getModel();
            int Myindex = tableBang.getSelectedRow();
            textMASV.setText(model.getValueAt(Myindex, 0).toString());
            txtHOVATen.setText(model.getValueAt(Myindex, 1).toString());
            txtLop.setText(model.getValueAt(Myindex, 3).toString());
            txtDiem.setText(model.getValueAt(Myindex, 4).toString());
            
    }//GEN-LAST:event_tableBangMouseClicked

    private void bntXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntXoaActionPerformed

    private void bntXoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntXoaMouseClicked
               textMASV.setText("");
               txtDiem.setText("");
               txtHOVATen.setText("");
               txtLop.setText("");
    }//GEN-LAST:event_bntXoaMouseClicked

    private void bntdeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntdeleteMouseClicked
        if (textMASV.getText().isEmpty()){
        
    JOptionPane.showMessageDialog(this, "Nhập sinh viên cần xóa");  
        }else {
            try {
               Con= DriverManager .getConnection("jdbc:sqlserver://localhost;encrypt=false;user=sa;password=123456;applicationName=LAPTOP-Q9EDFG23\\SQLEXPRESS;databaseName=DBBaiTapLon");
               String txtmaSV= textMASV.getText();
               String Query = "Delete from SinhVien where MaSV = "+txtmaSV;
               Statement Add= Con.createStatement();
               Add.executeUpdate(Query);
               JOptionPane.showMessageDialog(this, "Xóa sinh viên thành công");
                Con.close();
                SelectHSSV();
               
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_bntdeleteMouseClicked

    private void bntSuaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntSuaMouseClicked
          if(textMASV.getText().isEmpty()||txtHOVATen.getText().isEmpty()|| txtDiem.getText().isEmpty()||txtLop.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "không được để rỗng");
        }else{
              try {
                Con= DriverManager .getConnection("jdbc:sqlserver://localhost;encrypt=false;user=sa;password=123456;applicationName=LAPTOP-Q9EDFG23\\SQLEXPRESS;databaseName=DBBaiTapLon");
                String Query = "Update SinhVien set txtHOVaTen = '"+txtHOVATen.getText()+"'"+",txtDiem ='"+ txtDiem.getText()+"', txtLop='"+ txtLop.getText() +"',jcbChuyenNganh="+jcbChuyenNganh.getSelectedItem().toString()+"'"+ "Where txtMASV="+textMASV.getText();
                Statement Add = Con.createStatement();
                Add.executeUpdate(Query);
                JOptionPane.showConfirmDialog(this, "Cập nhật thành công");
                SelectHSSV(); 
                
                
              } catch (Exception e) {
                  e.printStackTrace();
              }
          }

    }//GEN-LAST:event_bntSuaMouseClicked

    private void bntdeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntdeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bntdeleteActionPerformed

    private void bntTimkiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bntTimkiemMouseClicked
       
        try {
             Con= DriverManager.getConnection("jdbc:sqlserver://localhost;encrypt=false;user=sa;password=123456;applicationName=LAPTOP-Q9EDFG23\\SQLEXPRESS;databaseName=DBBaiTapLon");
              String txtmaSV= txtTimKiem.getText();
              String masinhvien = "Select MaSV From SinhVien" + txtmaSV;
              Statement Add = Con.createStatement(); 
              Add.execute(masinhvien); 
              if( masinhvien.equals(txtTimKiem.getText())){
              new ThongTin().setVisible(true);
              this.dispose();
        }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_bntTimkiemMouseClicked
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HSSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HSSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HSSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HSSV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HSSV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntSua;
    private javax.swing.JButton bntTHem;
    private javax.swing.JButton bntTimkiem;
    private javax.swing.JButton bntXoa;
    private javax.swing.JButton bntdelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jcbChuyenNganh;
    private javax.swing.JTable tableBang;
    private javax.swing.JTextField textMASV;
    private javax.swing.JTextField txtDiem;
    private javax.swing.JTextField txtHOVATen;
    private javax.swing.JTextField txtLop;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
